repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-executables-have-shebangs
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
