
services:

  postgres:
    image: "postgres:13.3"
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql13/data
    networks:
      cooking:
        aliases:
          - "postgres"
    stop_grace_period: "3s"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


volumes:
  postgresql:
    driver: local
networks:
  cooking:
    driver: bridge
