
spring:
  application:
    name: cooking-backend
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        use_scrollable_resultset: true

elide:
  modelPackage: 'com.github.cookingbackend.model'
  json-api:
    path: /api
    enabled: true
  graphql:
    path: /graphql/api
    enabled: false
  swagger:
    path: /api-docs
    enabled: true
  async:
    enabled: false
  aggregation-store:
    enabled: false
  dynamic-config:
    enabled: false
