spring:
  application:
    name: cooking-backend
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        use_scrollable_resultset: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: "UTC"

  jackson:
    serialization:
      write-dates-as-timestamps: false


elide:
  modelPackage: 'com.github.cookingbackend.model'
  json-api:
    path: /api
    enabled: true
  graphql:
    path: /graphql/api
    enabled: false
  swagger:
    path: /api-docs
    enabled: true
    name: Cooking Backend Service
  async:
    enabled: false
  aggregation-store:
    enabled: false
  dynamic-config:
    enabled: false

server:
  tomcat:
    relaxed-query-chars: "[,]"
