name: Gradle CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: asdf-vm/actions/install@v1
        env:
          NODEJS_CHECK_SIGNATURES: no
      - name: Check
        run: |
          unset JAVA_HOME
          ./gradlew check --console=plain
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-reports
          path: build/reports/tests
